#!/usr/bin/env python3
"""
Migrate Durenn Vail from hand-crafted vestigial needs ("indulgence", "trader")
to the canonical need profile generated by compute_need_profile().

Preserves inventory and knowledge_base unchanged; only rebuilds the needs list
and updates credits.fills_need from "indulgence" → "leisure".
"""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from utilities.scenario_loader import load_scenario
from utilities.scenario_exporter import export_scenario
from logic.needs_config import compute_need_profile

DB_PATH   = os.path.join(os.path.dirname(__file__), "..", "scenarios", "wardens_compact.db")
VAIL_NAME = "Durenn Vail"


def migrate():
    state = load_scenario(DB_PATH)
    vail = next((m for m in state.mortals.values() if m.name == VAIL_NAME), None)
    if vail is None:
        print(f"ERROR: {VAIL_NAME} not found in {DB_PATH}")
        sys.exit(1)

    if vail.mortal_state is None:
        print(f"ERROR: {VAIL_NAME} has no mortal_state — run migrate_civilian_resources.py first")
        sys.exit(1)

    # Replace needs with trait-derived profile
    old_names = [n.name for n in vail.mortal_state.needs]
    vail.mortal_state.needs = compute_need_profile(vail.culture_tags)
    new_names = [n.name for n in vail.mortal_state.needs]
    print(f"Needs replaced: {old_names} → {new_names}")

    # Update credits resource: fills_need "indulgence" → "leisure"
    for res in vail.mortal_state.inventory:
        if res.fills_need == "indulgence":
            res.fills_need = "leisure"
            print(f"Updated {res.resource_type}.fills_need: indulgence → leisure")

    from pathlib import Path
    from utilities.scenario_migrator import _peek_scenario_meta
    name, description = _peek_scenario_meta(Path(DB_PATH))
    export_scenario(state, DB_PATH, scenario_name=name, description=description)
    print(f"Migration complete. Patched {VAIL_NAME} in {DB_PATH}.")

    # Print the resulting need profile for inspection
    print("\nDurenn Vail need profile:")
    for need in vail.mortal_state.needs:
        print(
            f"  {need.name:<12} decay={need.decay_rate:.4f}  "
            f"pressing={need.pressing_threshold:.3f}  urgent={need.urgent_threshold:.3f}"
        )


if __name__ == "__main__":
    migrate()
